### ISSUE TITLE
Ctrl + y interferes with native redo

### ISSUE THREAD

**Issue by johnrc** [iwehrman/brackets-kill-ring#3]
I know that key bindings are not currently addressed within Brackets, but you may consider changing kill ring's key binding as ctrl + y interferes with the native redo command. (I know other extensions have similar shortcut conflicts--just raising the issue.)

**Comment by iwehrman** [comment]
Thanks for pointing this out. I hadn't noticed because, on the Mac (where I spend most of my time), redo is bound to Cmd-Shift-Z instead of Ctrl-Y. And although I could find a different key to bind yank to, the point is to mimic the emacs shortcuts for the same operations, which I believe are the same across platforms. So I'm not sure how to resolve this conflict until Brackets has better support for profile-specific keyboard configuration. I'm open to suggestions!

**Comment by johnrc** [comment]
Thanks for the answer! I guess I need to spend more time on Macs because I didn't know it was a different shortcut... It makes sense to keep the emacs shortcuts and wait until Brackets has a better handle on keyboard bindings. I can change the key bindings manually in main.js or src/base-config/keyboard.json as needed.
